[project]
name = "repl-nix-globalcurrencytracker"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "plotly>=5.24.1",
    "requests>=2.32.3",
    "streamlit>=1.41.1",
]
